# Hallazgos

* No hay ids consecutivos
* Se tiene la altitud y longitud
* No se tiene directamente la alcandia pero se puede obtener mediante la libreria geopy
* Hay metrobuses que se encuentran en EdoMex
* Dentro del alrchivo del metrobus hay unas geolocalizaciones con errores

In [1]:
import pandas as pd
from geopy.geocoders import Nominatim

In [2]:
df = pd.read_csv('/home/david/metrobus_cdmx/data/prueba_fetchdata_metrobus.csv')
df

,id,date_updated,vehicle_id,vehicle_label,vehicle_current_status,position_latitude,position_longitude,geographic_point,position_speed,position_odometer,trip_schedule_relationship,trip_id,trip_start_date,trip_route_id
0,0,2021-01-27 18:00:02,170,112,2,19.317499,-99.187798,"19.3174991608,-99.1877975464",16,231,2,NaN,NaN,367.0
1,1,2021-01-27 18:00:02,177,119,1,19.292601,-99.177498,"19.2926006317,-99.1774978638",13,0,0,9732304.0,20200428.0,367.0
2,2,2021-01-27 18:00:02,1286,219,2,19.450100,-99.110100,"19.4500999451,-99.1100997925",5,0,0,9678929.0,20200428.0,161.0
3,3,2021-01-27 18:00:02,1302,235,1,19.389200,-99.059799,"19.3892002106,-99.0597991943",4,0,0,9738091.0,20200428.0,301.0
4,4,2021-01-27 18:00:02,361,303,2,19.382601,-99.061302,"19.3826007843,-99.0613021851",0,454,0,9738145.0,20200428.0,301.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,2021-01-27 18:00:02,1238,2347,2,19.403500,-99.169899,"19.4034996033,-99.1698989868",7,0,0,9736129.0,20200428.0,301.0
203,203,2021-01-27 18:00:02,1024,2351,2,19.390900,-99.047302,"19.3908996582,-99.0473022461",0,0,0,9737808.0,20200428.0,301.0
204,204,2021-01-27 18:00:02,10002,2358,2,19.397301,-99.104599,"19.3973007202,-99.104598999",7,0,0,9737246.0,20200428.0,301.0
205,205,2021-01-27 18:00:02,1232,2363,2,19.393900,-99.137497,"19.3938999176,-99.1374969482",14,0,0,9735896.0,20200428.0,301.0
206,206,2021-01-27 18:00:02,1235,2366,2,19.395100,-99.145798,"19.3950996399,-99.1457977295",0,276,0,9736965.0,20200428.0,301.0

# Información general

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          207 non-null    int64
 1   date_updated                207 non-null    object
 2   vehicle_id                  207 non-null    int64
 3   vehicle_label               207 non-null    int64
 4   vehicle_current_status      207 non-null    int64
 5   position_latitude           207 non-null    float64
 6   position_longitude          207 non-null    float64
 7   geographic_point            207 non-null    object
 8   position_speed              207 non-null    int64
 9   position_odometer           207 non-null    int64
 10  trip_schedule_relationship  207 non-null    int64
 11  trip_id                     172 non-null    float64
 12  trip_start_date             172 non-null    float64
 13  trip_route_id               180 non-null    float64
dtypes: float64(5), int64(7), object(2)
memory usage: 22.8+ KB

In [4]:
df.describe()

,id,vehicle_id,vehicle_label,vehicle_current_status,position_latitude,position_longitude,position_speed,position_odometer,trip_schedule_relationship,trip_id,trip_start_date,trip_route_id
count,207.000000,207.000000,207.00000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,1.720000e+02,172.0,180.000000
mean,103.000000,1109.507246,909.26570,1.710145,19.249019,-99.176083,4.492754,243.289855,0.338164,9.718865e+06,20200428.0,196.533333
std,59.899917,1711.173074,619.48861,0.454795,1.906558,0.428806,4.481753,374.391977,0.751466,3.115224e+04,0.0,122.958521
min,0.000000,1.000000,112.00000,1.000000,0.000000,-103.488998,0.000000,0.000000,0.000000,9.670725e+06,20200428.0,1.000000
25%,51.500000,500.500000,511.50000,1.000000,19.398000,-99.164101,0.000000,0.000000,0.000000,9.684345e+06,20200428.0,61.000000
50%,103.000000,789.000000,759.00000,2.000000,19.432100,-99.142998,4.000000,59.000000,0.000000,9.736082e+06,20200428.0,241.000000
75%,154.500000,1162.000000,1046.50000,2.000000,19.479751,-99.113899,7.500000,373.000000,0.000000,9.740058e+06,20200428.0,301.000000
max,206.000000,10023.000000,2376.00000,2.000000,19.527100,-99.047302,16.000000,1845.000000,2.000000,9.755750e+06,20200428.0,367.000000

# Atributos de interés

## vehicle_id

In [5]:
ids = df.vehicle_id.unique()
ids.sort()
ids

array([    1,     3,    20,    22,    23,    24,    26,    28,    33,
          35,    37,    38,    39,    40,    51,    53,    56,   170,
         177,   178,   361,   366,   367,   370,   371,   375,   398,
         409,   416,   422,   432,   449,   450,   452,   467,   472,
         473,   474,   475,   476,   482,   483,   484,   486,   490,
         491,   492,   494,   496,   497,   499,   500,   501,   502,
         504,   505,   506,   508,   509,   511,   512,   523,   531,
         533,   544,   545,   557,   558,   559,   560,   561,   562,
         701,   702,   705,   711,   713,   714,   716,   717,   719,
         720,   721,   728,   730,   737,   745,   746,   749,   753,
         754,   757,   758,   760,   764,   766,   770,   771,   774,
         777,   781,   787,   788,   789,   790,   930,   981,   982,
         984,   985,   986,   988,   990,   992,   997,  1018,  1021,
        1024,  1025,  1044,  1062,  1067,  1069,  1070,  1072,  1074,
        1075,  1078,  1079,  1084,  1085,  1089,  1091,  1100,  1101,
        1110,  1112,  1115,  1117,  1120,  1122,  1126,  1130,  1132,
        1135,  1141,  1144,  1146,  1147,  1148,  1149,  1151,  1152,
        1159,  1160,  1164,  1165,  1167,  1174,  1177,  1179,  1180,
        1181,  1184,  1185,  1186,  1188,  1190,  1191,  1192,  1214,
        1216,  1217,  1218,  1220,  1225,  1226,  1227,  1230,  1232,
        1233,  1234,  1235,  1236,  1237,  1238,  1241,  1248,  1253,
        1254,  1255,  1256,  1257,  1259,  1284,  1286,  1287,  1288,
        1289,  1302, 10000, 10002, 10007, 10015, 10016, 10019, 10023])

## position_latitude

In [6]:
df.position_latitude.unique()

array([19.31749916, 19.29260063, 19.45009995, 19.38920021, 19.38260078,
       19.38990021, 19.47920036, 19.40390015, 19.4034996 , 19.42700005,
       19.49160004, 19.42000008, 19.39710045, 19.40430069, 19.51199913,
       19.51729965, 19.50629997, 19.43770027, 19.52610016, 19.44280052,
       19.48399925, 19.43729973, 19.43610001, 19.42900085, 19.43560028,
       19.44499969, 19.4409008 , 19.4307003 , 19.42910004, 19.49740028,
       19.4321003 , 19.49530029, 19.47579956, 19.49069977, 19.4734993 ,
       19.48349953, 19.48749924, 19.45459938, 19.42580032, 19.45339966,
       19.45929909, 19.42679977, 19.42980003, 19.48730087, 19.44379997,
       19.39590073, 19.27939987, 19.41939926, 19.49889946, 19.41990089,
       19.39819908, 19.30170059, 19.44120026, 19.49729919, 19.49760056,
       19.40559959, 19.48220062, 19.48010063, 19.4041996 , 19.40449905,
       19.38430023, 19.3864994 , 19.39609909, 19.38640022, 19.39780045,
       19.39389992, 19.39579964, 19.37339973, 19.4510994 , 19.39080048,
       19.39649963, 19.40780067, 19.40460014, 19.40200043, 19.39450073,
       19.39100075, 19.52050018, 19.46069908, 19.47940063, 19.47360039,
       19.44619942, 19.44219971, 19.42519951, 19.43790054, 19.43040085,
       19.43050003, 19.42720032, 19.43099976, 19.43880081, 19.42609978,
       19.4253006 , 19.42970085, 19.4904995 , 19.50690079, 19.4598999 ,
       19.51180077, 19.4769001 , 19.49749947, 19.49189949, 19.48789978,
       19.48880005, 19.50699997, 19.49489975, 19.46910095,  0.        ,
       19.51110077, 19.46949959, 19.48380089, 19.48719978, 19.42810059,
       19.42420006, 19.4314003 , 19.49279976, 19.47850037, 19.49329948,
       19.38279915, 19.41279984, 19.30139923, 19.41959953, 19.41629982,
       19.48990059, 19.3526001 , 19.28300095, 19.49909973, 19.29870033,
       19.41609955, 19.4708004 , 19.3757    , 19.38979912, 19.39529991,
       19.39109993, 19.3871994 , 19.46489906, 19.4022007 , 19.42560005,
       19.49609947, 19.52709961, 19.44059944, 19.46579933, 19.43110085,
       19.43160057, 19.43810081, 19.43090057, 19.42329979, 19.44420052,
       19.4368    , 19.44470024, 19.47710037, 19.50720024, 19.46520042,
       19.47470093, 19.49810028, 19.50230026, 19.51040077, 19.46929932,
       19.5114994 , 19.49620056, 19.46730042, 19.47249985, 19.48800087,
       19.4647007 , 19.43519974, 19.42569923, 19.48679924, 19.42399979,
       19.49309921, 19.42690086, 19.49200058, 19.4272995 , 19.29649925,
       19.27910042, 19.49900055, 19.36459923, 19.44709969, 19.44129944,
       19.38909912, 19.39360046, 19.39769936, 19.38929939, 19.39089966,
       19.39730072, 19.39509964])

# position_longitude

In [7]:
df.position_longitude.unique()

array([ -99.18779755,  -99.17749786,  -99.11009979,  -99.05979919,
        -99.06130219,  -99.05889893,  -99.06390381,  -99.17240143,
        -99.17040253,  -99.14900208,  -99.15270233,  -99.15419769,
        -99.15589905,  -99.15540314,  -99.16049957,  -99.16269684,
        -99.15840149,  -99.14790344,  -99.16809845,  -99.14800262,
        -99.14980316,  -99.14589691,  -99.12139893,  -99.13210297,
        -99.11640167,  -99.15229797,  -99.15460205,  -99.15260315,
        -99.1155014 ,  -99.11430359,  -99.08969879,  -99.11509705,
        -99.15480042,  -99.08989716,  -99.13310242,  -99.07029724,
        -99.11389923,  -99.11380005,  -99.13020325,  -99.19309998,
        -99.13079834,  -99.12840271,  -99.19940186,  -99.16149902,
        -99.11370087,  -99.13909912,  -99.15660095,  -99.16899872,
        -99.16429901,  -99.11940002,  -99.16410065,  -99.1710968 ,
        -99.18589783,  -99.1548996 ,  -99.11969757,  -99.1855011 ,
        -99.10559845,  -99.10089874,  -99.1733017 ,  -99.17420197,
        -99.0759964 ,  -99.07949829,  -99.15910339,  -99.07189941,
        -99.12930298,  -99.09049988,  -99.15499878,  -99.17910004,
        -99.10970306,  -99.04730225,  -99.05619812,  -99.18920135,
        -99.18710327,  -99.14089966,  -99.04769897,  -99.10289764,
        -99.14389801,  -99.14820099,  -99.14600372,  -99.14710236,
        -99.15249634,  -99.11979675,  -99.1486969 ,  -99.14179993,
        -99.11620331,  -99.11540222,  -99.15319824,  -99.12999725,
        -99.12010193,  -99.13639832,  -99.09320068,  -99.08570099,
        -99.10579681,  -99.19609833,  -99.07250214,  -99.16459656,
        -99.13860321,  -99.11460114,  -99.12830353,  -99.19950104,
        -99.15339661,  -99.06410217, -103.48899841,  -99.1984024 ,
        -99.06469727,  -99.11779785,  -99.16500092,  -99.17389679,
        -99.12059784,  -99.14890289,  -99.1996994 ,  -99.12120056,
        -99.1210022 ,  -99.1760025 ,  -99.16629791,  -99.18579865,
        -99.16419983,  -99.16519928,  -99.12169647,  -99.17510223,
        -99.11959839,  -99.16529846,  -99.13749695,  -99.17839813,
        -99.05870056,  -99.04759979,  -99.08039856,  -99.05950165,
        -99.06159973,  -99.12950134,  -99.1867981 ,  -99.15470123,
        -99.14929962,  -99.15409851,  -99.15450287,  -99.1690979 ,
        -99.14859772,  -99.14299774,  -99.14810181,  -99.15029907,
        -99.14189911,  -99.13690186,  -99.14530182,  -99.1242981 ,
        -99.15239716,  -99.12689972,  -99.11219788,  -99.09889984,
        -99.08599854,  -99.09149933,  -99.08850098,  -99.1678009 ,
        -99.1785965 ,  -99.19860077,  -99.08529663,  -99.19760132,
        -99.15940094,  -99.11190033,  -99.08070374,  -99.12339783,
        -99.11440277,  -99.126297  ,  -99.15019989,  -99.17050171,
        -99.11799622,  -99.17990112,  -99.12090302,  -99.19979858,
        -99.12030029,  -99.16139984,  -99.18520355,  -99.16919708,
        -99.18199921,  -99.15309906,  -99.04949951,  -99.13200378,
        -99.1088028 ,  -99.05919647,  -99.16989899,  -99.104599  ,
        -99.14579773])

In [8]:
#Dataframe con datos mas relevantes
df = df[['vehicle_id', 'position_latitude', 'position_longitude']]
df

     vehicle_id  position_latitude  position_longitude
0           170          19.317499          -99.187798
1           177          19.292601          -99.177498
2          1286          19.450100          -99.110100
3          1302          19.389200          -99.059799
4           361          19.382601          -99.061302
..          ...                ...                 ...
202        1238          19.403500          -99.169899
203        1024          19.390900          -99.047302
204       10002          19.397301          -99.104599
205        1232          19.393900          -99.137497
206        1235          19.395100          -99.145798

[207 rows x 3 columns]

# Obtención de alcaldia por medio de geo points

In [9]:
def format_geographic_point(**kwargs):
    """
    Formateo del punto geografico
    """
    if 'position_latitude' in kwargs.keys() and 'position_longitude' in kwargs.keys():
        return str(kwargs['position_latitude']) + ', ' + str(kwargs['position_longitude'])
        
    return 'Error, formato no definido'

def get_location(data):
    
    if isinstance(data, str):
        geographic_point = data
    else:
        geographic_point = format_geographic_point(**data)
    
    geolocator = Nominatim(user_agent="http")
    location = geolocator.reverse(geographic_point)
    if location == None:
        return None
    
    location = location
    return location

In [10]:
# Obtencion de todos los geopoints
df['location'] = df[['position_latitude', 'position_longitude']].apply(get_location, axis=1)
df

<ipython-input-10-4b69aba7daaa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['location'] = df[['position_latitude', 'position_longitude']].apply(get_location, axis=1)

,vehicle_id,position_latitude,position_longitude,location
0,170,19.317499,-99.187798,"(Universidad Nacional Autónoma de México, Priv..."
1,177,19.292601,-99.177498,"(Ayuntamiento, Avenida Insurgentes Sur, Coloni..."
2,1286,19.450100,-99.110100,"(Avenida Ingeniero Eduardo Molina, Colonia 2o...."
3,1302,19.389200,-99.059799,"(Metrobús Linea 2, Unidad Habitacional Ejércit..."
4,361,19.382601,-99.061302,"(Avenida Canal de Tezontle, Colonia Leyes de R..."
...,...,...,...,...
202,1238,19.403500,-99.169899,"(Metrobús Linea 2, Colonia Hipódromo, Cuauhtém..."
203,1024,19.390900,-99.047302,"(Tepalcates, Metrobús Linea 2, Colonia Guelata..."
204,10002,19.397301,-99.104599,"(Metrobús, Colonia Gabriel Ramos Millán Secció..."
205,1232,19.393900,-99.137497,"(Metrobús, Colonia Moderna, Benito Juárez, Ciu..."
206,1235,19.395100,-99.145798,"(Xola, Unidad Habitacional IMSS Narvarte, Beni..."

In [11]:
# Ejemplo
df['location'].iloc[1]

Location(Ayuntamiento, Avenida Insurgentes Sur, Colonia Camiseta Calvario, Tlalpan, Ciudad de México, 14000, México, (19.2926512, -99.1776989, 0.0))

In [13]:
#Visualización de localicaiones
for location in df['location']:
    try:
        print(location[-2])
    except Exception as e:
        print(e)

Universidad Nacional Autónoma de México, Privada Juan B. Alberti, Colonia Copilco Universidad ISSSTE, Coyoacán, Ciudad de México, 04310, México
Ayuntamiento, Avenida Insurgentes Sur, Colonia Camiseta Calvario, Tlalpan, Ciudad de México, 14000, México
Avenida Ingeniero Eduardo Molina, Colonia 2o. tramo 20 de Noviembre, Venustiano Carranza, Ciudad de México, 15309, México
Metrobús Linea 2, Unidad Habitacional Ejército Constitucionalista, Iztapalapa, Ciudad de México, 09220, México
Avenida Canal de Tezontle, Colonia Leyes de Reforma 3a. Sección, Iztapalapa, Ciudad de México, 09310, México
Avenida Constitución de Apatzingán, Colonia Reforma Educativa, Iztapalapa, Ciudad de México, 09210, México
Metrobus, Calle Estado de Guanajuato, Gustavo A. Madero, Nezahualcóyotl, Ciudad de México, 07550, México
Metrobús Linea 2, Colonia Escandón, Miguel Hidalgo, Ciudad de México, 06100, México
Nuevo León 2, Metrobús Linea 2, Colonia Hipódromo, Cuauhtémoc, Ciudad de México, 06100, México
Balderas, Avenida Balderas, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, México
Calzada Vallejo, Colonia Nueva Vallejo, Gustavo A. Madero, Ciudad de México, 07750, México
Jardín Pushkin, Avenida Cuauhtémoc, Colonia Doctores, Cuauhtémoc, Ciudad de México, 06700, México
Etiopía / Plaza de la transparencia, Cuauhtémoc, Colonia Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México
Chevrolet Delta, Avenida Cuauhtémoc, Centro Urbano Benito Juárez, Cuauhtémoc, Ciudad de México, 06760, México
Calzada Vallejo, Colonia Ampliación Progreso Nacional, Gustavo A. Madero, Ciudad de México, 07650, México
Calle Vallejo, Gustavo A. Madero, Tlalnepantla, Tlalnepantla de Baz, Estado de México, 07650, México
Calzada Vallejo, Tlalnepantla, Tlalnepantla de Baz, Estado de México, 07710, México
Farmacias de Descuento, Avenida Hidalgo, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06300, México
Calzada Vallejo, Gustavo A. Madero, Ciudad de México, 07630, México
Guerrero, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
Calzada Vallejo, Colonia Nueva Vallejo, Gustavo A. Madero, Ciudad de México, 07750, México
Hidalgo, Avenida Hidalgo, Cuauhtémoc, Ciudad de México, 06300, México
Ferrocarril de Cintura, Calle Héroe de Nacozari, Colonia Penitenciaría, Venustiano Carranza, Ciudad de México, México
Plaza Comercial Oaxaca La Paja, Callejón del Conde, Centro Urbano, Cuauhtémoc, Ciudad de México, 06080, México
Calle Héroe de Nacozari, Colonia Penitenciaría, Venustiano Carranza, Ciudad de México, 15350, México
Metrobús Linea 4, Avenida Jesús García, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
Museo de la Revolucion Mexicana, Plaza de la República, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México
Calle Héroes Ferrocarrileros, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
San Lázaro Buena Vista ruta Sur, Avenida Ingeniero Eduardo Molina, Colonia 10 de Mayo, Venustiano Carranza, Ciudad de México, México
Calzada General Ignacio Zaragoza, Colonia 7 de Julio, Venustiano Carranza, Ciudad de México, 15390, México
5 de Mayo, Metrobus Línea 5, Gustavo A. Madero, Ciudad de México, México
Miguel Ramos Arizpe, Avenida Ingeniero Eduardo Molina, Colonia Penitenciaría, Venustiano Carranza, Ciudad de México, 15380, México
Avenida Poniente 140, Colonia Industrial Vallejo, Azcapotzalco, Ciudad de México, 02300, México
Puerto de Cozumel, Calzada San Juan de Aragón, Colonia FOVISSSTE Río de Guadalupe, Gustavo A. Madero, Ciudad de México, México
Avenida Montevideo, Colonia Lindavista, Gustavo A. Madero, Ciudad de México, 07300, México
Avenida 499, Colonia La Pradera, Gustavo A. Madero, Ciudad de México, 07918, México
Delegación Gustavo A. Madero, Metrobús Línea 7, Colonia Aragón, Gustavo A. Madero, Ciudad de México, 07050, México
43, Calle Hidalgo, Colonia Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07050, México
Monumento a los peregrinos, Calzada de los Misterios, Colonia Maza, Cuauhtémoc, Ciudad de México, 06250, México
Metro Auditorio, Metrobús Línea 7, Colonia Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11580, México
Peralvillo, Calzada de los Misterios, Colonia Maza, Cuauhtémoc, Ciudad de México, 06250, México
Calzada de los Misterios, Colonia Maza, Cuauhtémoc, Ciudad de México, 06250, México
Avenida Paseo de la Reforma, Colonia Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11580, México
Metrobús Línea 7, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06600, México
Hospital Infantil La Villa, Metrobús Línea 7, Colonia Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07050, México
Garibaldi, Metrobús Línea 7, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, México
Xola, Colonia Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México
El Caminero, Metrobús Linea 1, Barrio El Truenito, Tlalpan, Ciudad de México, 14090, México
Cumbé Coffee Roasters, Avenida Insurgentes Sur, Colonia Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México
Metrobús Linea 1, Colonia Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07369, México
Durango, Metrobús Línea 1, Colonia Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México
La Piedad, Metrobús Linea 1, Colonia Del Valle, Benito Juárez, Ciudad de México, 03810, México
CONABIO, Avenida Insurgentes Sur, Colonia Peña Pobre, Tlalpan, Ciudad de México, 14020, México
Oxxo, Avenida Insurgentes Centro, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06350, México
Metrobús Linea 1, Colonia Residencial Zacatenco, Gustavo A. Madero, Ciudad de México, 07369, México
Metrobús Linea 1, Colonia Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07369, México
Metrobús Linea 2, Colonia San Miguel Chapultepec, Miguel Hidalgo, Ciudad de México, 11870, México
Bancomer., Calzada San Juan de Aragón, Colonia Granjas Modernas, Gustavo A. Madero, Ciudad de México, 07469, México
Universidad Justo Sierra, Calzada San Juan de Aragón, Colonia Granjas Modernas, Gustavo A. Madero, Ciudad de México, 07460, México
Metrobús Linea 2, Colonia Escandón, Miguel Hidalgo, Ciudad de México, 06100, México
Metrobús Linea 2, Colonia Hipódromo de la Condesa, Cuauhtémoc, Ciudad de México, 06100, México
Rojo Gómez, Metrobús Linea 2, Colonia Cuchillas del Moral II y III, Iztapalapa, Ciudad de México, 09020, México
Avenida San Rafaél Atlixco, Colonia Dr. Alfonso Ortiz Tirado, Iztapalapa, Ciudad de México, 09020, México
Metrobús, Colonia Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México
Metrobús Linea 2, Colonia INFONAVIT Sur 20, Iztacalco, Ciudad de México, 08500, México
Andrés Molina, Metrobús, Colonia Nueva Santa Anita, Iztacalco, Ciudad de México, 08210, México
Avenida Té, Ex Ejido Magdalena Mixhuca, Iztacalco, Ciudad de México, 08000, México
Café Fuerte, Xola, Colonia Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México
Metrobús Linea 1, Colonia Extremadura Insurgentes, Benito Juárez, Ciudad de México, 03230, México
mercado rastro, Avenida Ingeniero Eduardo Molina, Colonia 2o. tramo 20 de Noviembre, Venustiano Carranza, Ciudad de México, México
Tepalcates, Metrobús Linea 2, Colonia Guelatao Benito Juárez, Iztapalapa, Ciudad de México, 09220, México
Metrobús Linea 2, Iztapalapa, Ciudad de México, 09210, México
76, Calle Gobernador Agustín Vicente Eguía, Colonia Ampliación Daniel Garza, Miguel Hidalgo, Ciudad de México, 11850, México
Avenida Benjamín Franklin, Colonia Hipódromo, Cuauhtémoc, Ciudad de México, 06100, México
Tacubaya, Avenida Parque Lira, Colonia Tacubaya, Miguel Hidalgo, Ciudad de México, 11870, México
Metrobús, Unidad Habitacional IMSS Narvarte, Benito Juárez, Ciudad de México, 03400, México
Metrobús Linea 2, Colonia Reforma Educativa, Iztapalapa, Ciudad de México, 09210, México
Metrobús, Colonia Gabriel Ramos Millán Sección Tlacotal, Iztacalco, Ciudad de México, 08400, México
Calzada Vallejo, Colonia Ampliación Progreso Nacional, Gustavo A. Madero, Ciudad de México, 07600, México
Prolongación Guerrero, Colonia San Simón Tolnahuac, Cuauhtémoc, Ciudad de México, 06420, México
Coltongo, Calzada Vallejo, Colonia Magdalena de Las Salinas, Gustavo A. Madero, Azcapotzalco, Ciudad de México, 02630, México
Etiopía / Plaza de la transparencia, Cuauhtémoc, Colonia Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México
Calzada Vallejo, Colonia El Porvenir, Azcapotzalco, Ciudad de México, 02940, México
Hotel Lepanto, Guerrero, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06300, México
Calle Buenavista, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
Cecilio Robelo, Avenida Congreso de la Unión, Colonia Morelos II, Venustiano Carranza, Ciudad de México, México
Farmacias de Descuento, Avenida Hidalgo, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06300, México
Metrobús Eje Central, Calle Ayuntamiento, Centro Urbano, Cuauhtémoc, Ciudad de México, 06050, México
San Lázaro, Avenida Ingeniero Eduardo Molina, Colonia 7 de Julio, Venustiano Carranza, Ciudad de México, México
IEMS "José Revueltas Sánchez", Calle Sidar y Rovirosa, Colonia Morazán, Venustiano Carranza, Ciudad de México, 15960, México
San Lázaro Buena Vista ruta Sur, Avenida Ingeniero Eduardo Molina, Colonia 10 de Mayo, Venustiano Carranza, Ciudad de México, México
Nacional Monte de Piedad, Av. México-Tenochtitlán, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México
Centro Urbano, Cuauhtémoc, Ciudad de México, 06080, México
Calle Unión, Colonia Morazán, Venustiano Carranza, Ciudad de México, 15100, México
Ex-iglesia de San Agustín / Ex-Biblioteca Nacional, 69, Calle República de Uruguay, Centro Urbano, Cuauhtémoc, Ciudad de México, 06000, México
Metrobus Línea 5, Colonia Ampliación Mártires de Río Blanco, Gustavo A. Madero, Ciudad de México, 07858, México
Río de los Remedios, Metrobus Línea 5, Colonia Ampliación Mártires de Río Blanco, Gustavo A. Madero, Ciudad de México, México
Metrobus Línea 5, Colonia San Pedro El Chico, Ciudad de México, 07890, México
Avenida de las Culturas, Colonia El Rosario CROC VI Oyameles, Colonia El Rosario CROC VI Olimpia, Azcapotzalco, Ciudad de México, 02100, México
Volcán de Fuego, Avenida Francisco Morazán, Colonia Ampliación Providencia, Gustavo A. Madero, Ciudad de México, 07560, México
Avenida Poniente 140, Colonia Industrial Vallejo, Azcapotzalco, Ciudad de México, 02300, México
San Bartolo, Avenida Montevideo, Colonia San Bartolo Atepehuacan, Gustavo A. Madero, Ciudad de México, 07730, México
Universidad ICEL, Avenida Cantera, Colonia Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07050, México
Avenida Montevideo, Colonia Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07300, México
El Rosario, Calle Cultura Norte, Colonia El Rosario CROC VI Oyameles, Colonia El Rosario CROC VIII, Azcapotzalco, Ciudad de México, 02100, México
Industronic, Avenida Poniente 140, Colonia Nueva Industrial Vallejo, Gustavo A. Madero, Ciudad de México, 07750, México
680, Avenida Francisco Morazán, Colonia Malvinas Mexicanas, Gustavo A. Madero, Ciudad de México, 07509, México
'NoneType' object is not subscriptable
Calle Cultura Norte, Colonia El Rosario CROC VI Oyameles, Colonia El Rosario CROC VIII, Azcapotzalco, Ciudad de México, 02100, México
Avenida Francisco Morazán, Colonia Malvinas Mexicanas, Gustavo A. Madero, Ciudad de México, 07918, México
Metrobús Línea 7, Colonia 7 de Noviembre, Gustavo A. Madero, Ciudad de México, 07050, México
43, Calle Hidalgo, Colonia Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07050, México
La Palma, Metrobús Línea 7, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06600, México
Chapultepec, Metrobús Línea 7, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, México
Avenida Paseo de la Reforma, Colonia Juárez, Cuauhtémoc, Ciudad de México, 06600, México
Indios Verdes, Metrobús Línea 7, Colonia Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07369, México
Avenida Paseo de la Reforma Norte, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México
Campo Marte, Metrobús Línea 7, Colonia Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11580, México
Calzada de los Misterios, Colonia Industrial, Gustavo A. Madero, Ciudad de México, 07800, México
Avenida Prolongación Misterios, Colonia Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07020, México
'NoneType' object is not subscriptable
Indios Verdes, Metrobús Línea 7, Colonia Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07369, México
Avenida Paseo de la Reforma, Colonia Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11580, México
Metrobús Linea 1, Colonia Insurgentes San Borja, Benito Juárez, Ciudad de México, 03710, México
Avenida Sonora, Colonia Hipódromo, Cuauhtémoc, Ciudad de México, 06700, México
Avenida Insurgentes Sur, Colonia Zona Arqueológica de Cuicuilco, Tlalpan, Ciudad de México, 14060, México
Durango, Metrobús Línea 1, Colonia Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México
Álvaro Obregón, Metrobús Línea 1, Colonia Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México
Metrobús Linea 1, Colonia Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07369, México
1940, Avenida Insurgentes Sur, Colonia Guadalupe Inn, Álvaro Obregón, Ciudad de México, 01030, México
Metrobús Linea 1, Unidad Habitacional Residencial Insurgentes Sur, Tlalpan, Ciudad de México, 14420, México
Metrobús Linea 1, Colonia Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07369, México
SEDESOL - DICONSA, Avenida Insurgentes Sur, Colonia Peña Pobre, Tlalpan, Ciudad de México, 14020, México
Transbordo Intermodal MB Álvaro Obregón, Colonia Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México
Carril Bus-Bici, Unidad Habitacional Nonoalco Tlatelolco, Cuauhtémoc, Ciudad de México, 06900, México
Konditori, 1261, Avenida Insurgentes Sur, Colonia Extremadura Insurgentes, Benito Juárez, Ciudad de México, 03740, México
Avenida Constitución de Apatzingán, Colonia Reforma Educativa, Iztapalapa, Ciudad de México, 09210, México
Xola, Unidad Habitacional IMSS Narvarte, Benito Juárez, Ciudad de México, 03023, México
Metrobús Linea 2, Colonia Reforma Educativa, Iztapalapa, Ciudad de México, 09210, México
Avenida Constitución de Apatzingán, Colonia Reforma Educativa, Iztapalapa, Ciudad de México, 09210, México
Río Mayo, Metrobús, Colonia Dr. Alfonso Ortiz Tirado, Iztapalapa, Ciudad de México, 09020, México
Avenida Constitución de Apatzingán, Unidad Habitacional Ejército Constitucionalista, Iztapalapa, Ciudad de México, 09210, México
Metrobús Linea 2, Colonia Reforma Educativa, Iztapalapa, Ciudad de México, 09210, México
Metrobús Linea 2, Colonia INFONAVIT Sur 20, Iztacalco, Ciudad de México, 08500, México
Avenida Francisco Morazán, Colonia Villa de Aragón, Gustavo A. Madero, Ciudad de México, 07918, México
Andrés Molina, Metrobús, Colonia Nueva Santa Anita, Iztacalco, Ciudad de México, 08210, México
Coppel Tacubaya, Metrobús Linea 2, Colonia Tacubaya, Miguel Hidalgo, Ciudad de México, México
Potzolcalli, Avenida Cuauhtémoc, Centro Urbano Benito Juárez, Cuauhtémoc, Ciudad de México, México
Avenida Balderas, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06040, México
Avenida Cuauhtémoc, Colonia Doctores, Cuauhtémoc, Ciudad de México, 06720, México
Pan el saso, Calzada Vallejo, Colonia Magdalena de Las Salinas, Gustavo A. Madero, Ciudad de México, 07760, México
Montevideo, Calzada Vallejo, Colonia San Andrés de Las Salinas, Azcapotzalco, Ciudad de México, 02300, México
1856, Calzada Vallejo, Gustavo A. Madero, Ciudad de México, 07620, México
Guerrero, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
Calzada Vallejo, Colonia Vallejo Poniente, Gustavo A. Madero, Ciudad de México, 07790, México
Avenida Balderas, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06070, México
Metrobús Vocacional 5, Calle Ayuntamiento, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06040, México
Metrobús Eje Central, Calle Ayuntamiento, Centro Urbano, Cuauhtémoc, Ciudad de México, 06050, México
El Mesón de Belosario 38 Traditional comida Mexicana, 38, Calle Belisario Domínguez, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México
XEW-AM, Calle Ayuntamiento, Centro Urbano, Cuauhtémoc, Ciudad de México, 06050, México
Mercado Sonora, Calle Juan Cuamatzín, Colonia Morazán, Venustiano Carranza, Ciudad de México, México
Suburbia, Calle Carlos J. Meneses, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
Teatro del Pueblo, Calle General Miguel Alemán, Cuauhtémoc, Ciudad de México, 06020, México
Metrobús Linea 4, Avenida Jesús García, Colonia Buenavista, Cuauhtémoc, Ciudad de México, 06350, México
Deportivo Eduardo Molina, Avenida Ingeniero Eduardo Molina, Colonia Ampliación 20 de Noviembre, Venustiano Carranza, Ciudad de México, 15260, México
Metrobus Línea 5, Colonia Ampliación Mártires de Río Blanco, Gustavo A. Madero, Ciudad de México, 07858, México
Río de los Remedios, Metrobus Línea 5, Colonia Ampliación Mártires de Río Blanco, Gustavo A. Madero, Ciudad de México, México
Vasco de Quiroga, Metrobus Línea 5, Gustavo A. Madero, Ciudad de México, México
Avenida Francisco Morazán, Colonia Villa de Aragón, Gustavo A. Madero, Ciudad de México, 07918, México
660, Calzada San Juan de Aragón, Colonia FOVISSSTE Río de Guadalupe, Gustavo A. Madero, Ciudad de México, 07920, México
Avenida Poniente 140, Colonia Industrial Vallejo, Colonia Ferrería, Azcapotzalco, Ciudad de México, 02300, México
Tecnoparque, Avenida Deportivo Reynosa, Colonia Nueva ampliación El Rosario, Colonia San Pablo Xalpa, Azcapotzalco, Ciudad de México, 02230, México
Calle Cultura Norte, Colonia El Rosario CROC VI Oyameles, Colonia El Rosario CROC VIII, Azcapotzalco, Ciudad de México, 02100, México
Calzada San Juan de Aragón, Colonia San Juan de Aragón, Gustavo A. Madero, Ciudad de México, 07950, México
Avenida de las Culturas, Colonia INFONAVIT EL ROSARIO, Colonia El Rosario CROC VIII, Azcapotzalco, Ciudad de México, 02100, México
Total, Avenida Poniente 140, Colonia Industrial Vallejo, Colonia Ferrería, Azcapotzalco, Ciudad de México, 02300, México
Calzada San Juan de Aragón, Colonia 15 de Agosto, Gustavo A. Madero, Ciudad de México, 07058, México
Loreto Fabela, Avenida Río de Guadalupe, Colonia San Juan de Aragón, Gustavo A. Madero, Ciudad de México, 07950, México
Calzada de los Misterios (Metrobús Línea 7), Colonia Industrial, Gustavo A. Madero, Ciudad de México, 07800, México
Centro de Atención Multiple N°18, Avenida Cantera, Colonia Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07050, México
Clave, Calzada de los Misterios, Colonia 7 de Noviembre, Gustavo A. Madero, Ciudad de México, 07870, México
Avenida Paseo de la Reforma, Colonia Tabacalera, Cuauhtémoc, Ciudad de México, 06040, México
Avenida Paseo de la Reforma, Colonia Cuauhtémoc, Cuauhtémoc, Ciudad de México, 06500, México
Calzada de los Misterios, Colonia Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07050, México
Avenida Paseo de la Reforma, Colonia Nueva Anzures, Miguel Hidalgo, Ciudad de México, 11580, México
Hospital Infantil La Villa, Metrobús Línea 7, Colonia Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07050, México
Indios Verdes, Metrobús Línea 7, Colonia Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07369, México
Avenida Paseo de la Reforma, Colonia Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11580, México
Metrobús Linea 1, Colonia Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07020, México
Avenida Insurgentes Sur, Colonia Juárez, Cuauhtémoc, Ciudad de México, 06600, México
Inbursa, Avenida Insurgentes Sur, Colonia Peña Pobre, Tlalpan, Ciudad de México, 14060, México
El Caminero, Metrobús Linea 1, Barrio El Truenito, Tlalpan, Ciudad de México, 14090, México
Metrobús Linea 1, Colonia Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07369, México
Hotel City Express, Avenida Insurgentes Sur, Colonia Crédito constructor, Benito Juárez, Ciudad de México, 03900, México

In [25]:
get_location('19.4792003631592, -99.0639038085938')

Location(Metrobus, Calle Estado de Guanajuato, Gustavo A. Madero, Nezahualcóyotl, Ciudad de México, 07550, México, (19.4789599, -99.06411161417999, 0.0))

## Obtención de alcaldias

In [15]:
def get_alcaldia(data):
    location = get_location(data)
    if location == None:
        return 'N/A'
    
    location = list(location)[0]
        
#    print(location)
    location_list = location.split(', ')
    
    if 'Ciudad de México' in location_list:
        entidad = 'Ciudad de México'
    elif 'Estado de México' in location_list:
        entidad = 'Estado de México'
        
    index_referencia = location_list.index(entidad)
    
    index_referencia = index_referencia - 1
#    print(index_referencia)
    alcaldia = location_list[index_referencia]
    print(alcaldia)
    return alcaldia

In [23]:
# Ejemplo de alcaldia por medio de geopoints
get_alcaldia('19.4792003631592, -99.0639038085938')

Nezahualcóyotl

'Nezahualcóyotl'

In [17]:
#alcaldias del df
df['alcaldia'] = df[['position_latitude', 'position_longitude']].apply(get_alcaldia, axis=1)
df

Coyoacán
Tlalpan
Venustiano Carranza
Iztapalapa
Iztapalapa
Iztapalapa
Nezahualcóyotl
Miguel Hidalgo
Cuauhtémoc
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Benito Juárez
Cuauhtémoc
Gustavo A. Madero
Tlalnepantla de Baz
Tlalnepantla de Baz
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Venustiano Carranza
Cuauhtémoc
Venustiano Carranza
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Venustiano Carranza
Venustiano Carranza
Gustavo A. Madero
Venustiano Carranza
Azcapotzalco
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Cuauhtémoc
Miguel Hidalgo
Cuauhtémoc
Cuauhtémoc
Miguel Hidalgo
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Benito Juárez
Tlalpan
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Benito Juárez
Tlalpan
Cuauhtémoc
Gustavo A. Madero
Gustavo A. Madero
Miguel Hidalgo
Gustavo A. Madero
Gustavo A. Madero
Miguel Hidalgo
Cuauhtémoc
Iztapalapa
Iztapalapa
Benito Juárez
Iztacalco
Iztacalco
Iztacalco
Benito Juárez
Benito Juárez
Venustiano Carranza
Iztapalapa
Iztapalapa
Miguel Hidalgo
Cuauhtémoc
Miguel Hidalgo
Benito Juárez
Iztapalapa
Iztacalco
Gustavo A. Madero
Cuauhtémoc
Azcapotzalco
Benito Juárez
Azcapotzalco
Cuauhtémoc
Cuauhtémoc
Venustiano Carranza
Cuauhtémoc
Cuauhtémoc
Venustiano Carranza
Venustiano Carranza
Venustiano Carranza
Cuauhtémoc
Cuauhtémoc
Venustiano Carranza
Cuauhtémoc
Gustavo A. Madero
Gustavo A. Madero
Colonia San Pedro El Chico
Azcapotzalco
Gustavo A. Madero
Azcapotzalco
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Azcapotzalco
Gustavo A. Madero
Gustavo A. Madero
Azcapotzalco
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Miguel Hidalgo
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Miguel Hidalgo
Benito Juárez
Cuauhtémoc
Tlalpan
Cuauhtémoc
Cuauhtémoc
Gustavo A. Madero
Álvaro Obregón
Tlalpan
Gustavo A. Madero
Tlalpan
Cuauhtémoc
Cuauhtémoc
Benito Juárez
Iztapalapa
Benito Juárez
Iztapalapa
Iztapalapa
Iztapalapa
Iztapalapa
Iztapalapa
Iztacalco
Gustavo A. Madero
Iztacalco
Miguel Hidalgo
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Gustavo A. Madero
Azcapotzalco
Gustavo A. Madero
Cuauhtémoc
Gustavo A. Madero
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Venustiano Carranza
Cuauhtémoc
Cuauhtémoc
Cuauhtémoc
Venustiano Carranza
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Azcapotzalco
Azcapotzalco
Azcapotzalco
Gustavo A. Madero
Azcapotzalco
Azcapotzalco
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Gustavo A. Madero
Cuauhtémoc
Cuauhtémoc
Gustavo A. Madero
Miguel Hidalgo
Gustavo A. Madero
Gustavo A. Madero
Miguel Hidalgo
Gustavo A. Madero
Cuauhtémoc
Tlalpan
Tlalpan
Gustavo A. Madero
Benito Juárez
Cuauhtémoc
Cuauhtémoc
Gustavo A. Madero
Iztapalapa
Iztacalco
Iztacalco
Iztapalapa
Iztacalco
Cuauhtémoc
Iztapalapa
Iztacalco
Benito Juárez
Benito Juárez

<ipython-input-17-fa971ace3e91>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['alcaldia'] = df[['position_latitude', 'position_longitude']].apply(get_alcaldia, axis=1)

,vehicle_id,position_latitude,position_longitude,location,alcaldia
0,170,19.317499,-99.187798,"(Universidad Nacional Autónoma de México, Priv...",Coyoacán
1,177,19.292601,-99.177498,"(Ayuntamiento, Avenida Insurgentes Sur, Coloni...",Tlalpan
2,1286,19.450100,-99.110100,"(Avenida Ingeniero Eduardo Molina, Colonia 2o....",Venustiano Carranza
3,1302,19.389200,-99.059799,"(Metrobús Linea 2, Unidad Habitacional Ejércit...",Iztapalapa
4,361,19.382601,-99.061302,"(Avenida Canal de Tezontle, Colonia Leyes de R...",Iztapalapa
...,...,...,...,...,...
202,1238,19.403500,-99.169899,"(Metrobús Linea 2, Colonia Hipódromo, Cuauhtém...",Cuauhtémoc
203,1024,19.390900,-99.047302,"(Tepalcates, Metrobús Linea 2, Colonia Guelata...",Iztapalapa
204,10002,19.397301,-99.104599,"(Metrobús, Colonia Gabriel Ramos Millán Secció...",Iztacalco
205,1232,19.393900,-99.137497,"(Metrobús, Colonia Moderna, Benito Juárez, Ciu...",Benito Juárez
206,1235,19.395100,-99.145798,"(Xola, Unidad Habitacional IMSS Narvarte, Beni...",Benito Juárez

In [18]:
alcaldias = df.alcaldia.unique()
alcaldias.sort()
alcaldias

array(['Azcapotzalco', 'Benito Juárez', 'Colonia San Pedro El Chico',
       'Coyoacán', 'Cuauhtémoc', 'Gustavo A. Madero', 'Iztacalco',
       'Iztapalapa', 'Miguel Hidalgo', 'N/A', 'Nezahualcóyotl',
       'Tlalnepantla de Baz', 'Tlalpan', 'Venustiano Carranza',
       'Álvaro Obregón'], dtype=object)

## Revisión del alcaldias de cdmx

In [19]:
df2 = pd.read_csv('/home/david/metrobus_cdmx/data/limite-de-las-alcaldias.csv')
df2

,id,nomgeo,cve_mun,cve_ent,cvegeo,gid,geo_point_2d,geo_shape
0,0,Xochimilco,13,9,9013,5,"19.2451450458,-99.0903636045","{""type"": ""Polygon"", ""coordinates"": [[[-99.0986..."
1,1,Cuauhtémoc,15,9,9015,13,"19.4313734294,-99.1490557562","{""type"": ""Polygon"", ""coordinates"": [[[-99.1291..."
2,2,Iztacalco,6,9,9006,2,"19.396911897,-99.094329797","{""type"": ""Polygon"", ""coordinates"": [[[-99.0558..."
3,3,Álvaro Obregón,10,9,9010,4,"19.336175562,-99.246819712","{""type"": ""Polygon"", ""coordinates"": [[[-99.1887..."
4,4,Coyoacán,3,9,9003,7,"19.3266672536,-99.1503763525","{""type"": ""Polygon"", ""coordinates"": [[[-99.1392..."
5,5,Tlalpan,12,9,9012,8,"19.1983396763,-99.2062207957","{""type"": ""Polygon"", ""coordinates"": [[[-99.1962..."
6,6,Gustavo A. Madero,5,9,9005,12,"19.5040652077,-99.1158642087","{""type"": ""Polygon"", ""coordinates"": [[[-99.1185..."
7,7,Iztapalapa,7,9,9007,15,"19.3491663204,-99.0567989642","{""type"": ""Polygon"", ""coordinates"": [[[-99.0581..."
8,8,Azcapotzalco,2,9,9002,1,"19.4853286147,-99.1821069423","{""type"": ""Polygon"", ""coordinates"": [[[-99.1823..."
9,9,Milpa Alta,9,9,9009,3,"19.1394565999,-99.0510954218","{""type"": ""Polygon"", ""coordinates"": [[[-98.9972..."
10,10,Venustiano Carranza,17,9,9017,6,"19.4304954545,-99.0931057959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1089..."
11,11,Benito Juárez,14,9,9014,9,"19.3806424162,-99.1611346584","{""type"": ""Polygon"", ""coordinates"": [[[-99.1367..."
12,12,Cuajimalpa de Morelos,4,9,9004,10,"19.3246343001,-99.3107285253","{""type"": ""Polygon"", ""coordinates"": [[[-99.2569..."
13,13,Miguel Hidalgo,16,9,9016,11,"19.4280623649,-99.2045669144","{""type"": ""Polygon"", ""coordinates"": [[[-99.1905..."
14,14,La Magdalena Contreras,8,9,9008,14,"19.2689765031,-99.2684129061","{""type"": ""Polygon"", ""coordinates"": [[[-99.2085..."
15,15,Tláhuac,11,9,9011,16,"19.2769983772,-99.0028216137","{""type"": ""Polygon"", ""coordinates"": [[[-98.9789..."

In [20]:
alcaldias_df = df2.nomgeo

In [21]:
alcaldias_complemento = set(alcaldias) - set(alcaldias_df)

In [22]:
#ubicaciones en EdoMex o con error por falta de información en geopoints
df[df['alcaldia'].isin(alcaldias_complemento)]

,vehicle_id,position_latitude,position_longitude,location,alcaldia
6,371,19.4792,-99.063904,"(Metrobus, Calle Estado de Guanajuato, Gustavo...",Nezahualcóyotl
15,1148,19.5173,-99.162697,"(Calle Vallejo, Gustavo A. Madero, Tlalnepantl...",Tlalnepantla de Baz
16,1149,19.5063,-99.158401,"(Calzada Vallejo, Tlalnepantla, Tlalnepantla d...",Tlalnepantla de Baz
97,1179,19.4599,-99.105797,"(Metrobus Línea 5, Colonia San Pedro El Chico,...",Colonia San Pedro El Chico
107,1135,0.0000,-103.488998,None,N/A
120,781,0.0000,-103.488998,None,N/A